### ISSUE TITLE
Development Tooling and Automated Setup for Ubuntu

### ISSUE THREAD

**Issue by christopherkeim** [unna97/audio-annonation#29]
**Is your feature request related to a problem? Please describe.**
DevOps infrastructure for automated development environment setup as well as source code linting, formatting, and testing optimizes development workflows. 

**Describe the solution you'd like**

We'll need:

1. `setup.sh`: for automated development environment set up (targets are poetry 1.5.1, Python3.11, PostgresSQL 16, and Docker 24.0.6)
2. `Makefile`: with commands for installing Python dependencies, linting, formatting, and testing

**Describe alternatives you've considered**
Ubuntu is the development and deployment target.

**Additional context**
Software versions may change as development progresses, but the base infrastructure is important.

**Comment by unna97** [comment]
#31 Addresses setup.sh
